"use server";

import { redirect } from"next/navigation";
import { checkUserOrganization } from"@/server/actions/onboarding";
import { getBillingPortalDataAction } from"@/server/actions/billing";
import { BillingPortalClient } from"@/components/forms/billing-portal-client";
import { PageTitle } from"@/components/shared/page-title";
import { BarChartCard } from"@/components/charts";

export default async function BillingPage() {
 const { hasOrg } = await checkUserOrganization();
 if (!hasOrg) {
 redirect("/onboarding");
 }

 const response = await getBillingPortalDataAction();

 if (!response.success) {
 return (
 <div className="flex h-96 flex-col items-center justify-center text-center p-space-8 border border-[hsl(var(--foreground)/0.06)] radius-lg bg-[hsl(var(--foreground)/0.02)]">
 <h3 className="text-body-md text-foreground">Couldn’t load billing</h3>
 <p className="text-body-sm text-muted-foreground mt-space-2">
 This is usually temporary. Try refreshing the page.
 </p>
 </div>
 );
 }

 const initialSubscription = response.subscription;
 const initialAccount = response.account;
 const initialInvoices = response.invoices || [];
 const initialPayments = response.payments || [];
 const initialUsageCounters = response.usageCounters || [];

 return (
 <div className="space-y-space-8 animate-fade-in max-w-5xl">
 {/* Page Header */}
 <PageTitle
 title="Billing & Revenue"
 description="Your plan, usage, payment history, and revenue forecast."
 />

 {/* Revenue Forecast Chart */}
 <div className="grid grid-cols-1 gap-space-4 shrink-0">
 <div className="bg-white dark:bg-card border border-border-default radius-xl overflow-hidden flex flex-col">
 <div className="p-space-5 pb-space-2 shrink-0">
 <h3 className="text-body-sm font-semibold">Revenue Forecast</h3>
 <p className="text-caption text-muted-foreground">Estimated revenue generated by AI bookings</p>
 </div>
 <div className="flex-1 p-space-5 pt-0">
 <BarChartCard 
 data={[
 { month:"Jan", revenue: 4500 },
 { month:"Feb", revenue: 5200 },
 { month:"Mar", revenue: 6100 },
 { month:"Apr", revenue: 7800 },
 { month:"May", revenue: 9500 },
 { month:"Jun", revenue: 11200 },
 ]}
 index="month"
 categories={["revenue"]}
 colors={["#10b981"]}
 height={260}
 />
 </div>
 </div>
 </div>

 <BillingPortalClient 
 initialSubscription={initialSubscription}
 initialAccount={initialAccount}
 initialInvoices={initialInvoices}
 initialPayments={initialPayments}
 initialUsageCounters={initialUsageCounters}
 />
 </div>
 );
}
